account:
  name:
  pwd:
  cookieFilePath: './my.cookies'
  eid:
  fp:
  trackId:
  riskControl:
  sku:
    allow: true
    id: '2132134324234'
    count: 1
    reserveTime: '2020-12-31'
    buyTime: '2020-12-31'
