account:
  pwd:
  cookieFilePath: './my.cookies'
  eid:
  fp:
  trackId:
  riskControl:
  sku:
    id: '2132134324234'
    count: 1
    #时间格式time.RFC3339 "2009-01-01T01:02:01.100+08:00"
    buyTime: '2020-12-31'
